namespace Docker.DotNet;

[JsonSourceGenerationOptions(Converters = [
    typeof(JsonEnumMemberConverter<RestartPolicyKind>),
    typeof(JsonEnumMemberConverter<TaskState>),
    typeof(JsonDateTimeConverter),
    typeof(JsonNullableDateTimeConverter),
    typeof(JsonBase64Converter),
])]
[JsonSerializable(typeof(AuthConfig))]
[JsonSerializable(typeof(CommitContainerChangesParameters))]
[JsonSerializable(typeof(CommitContainerChangesResponse))]
[JsonSerializable(typeof(ContainerExecCreateParameters))]
[JsonSerializable(typeof(ContainerExecCreateResponse))]
[JsonSerializable(typeof(ContainerExecInspectResponse))]
[JsonSerializable(typeof(ContainerExecStartParameters))]
[JsonSerializable(typeof(ContainerFileSystemChangeResponse[]))]
[JsonSerializable(typeof(ContainerInspectResponse))]
[JsonSerializable(typeof(ContainerListResponse[]))]
[JsonSerializable(typeof(ContainerPathStatResponse))]
[JsonSerializable(typeof(ContainerProcessesResponse))]
[JsonSerializable(typeof(ContainerStatsResponse))]
[JsonSerializable(typeof(ContainerUpdateParameters))]
[JsonSerializable(typeof(ContainerUpdateResponse))]
[JsonSerializable(typeof(ContainerWaitResponse))]
[JsonSerializable(typeof(ContainersPruneResponse))]
[JsonSerializable(typeof(CreateContainerParameters))]
[JsonSerializable(typeof(CreateContainerResponse))]
[JsonSerializable(typeof(Dictionary<string, AuthConfig>))]
[JsonSerializable(typeof(Dictionary<string, string>[]))]
[JsonSerializable(typeof(IDictionary<string, IDictionary<string, bool>>))]
[JsonSerializable(typeof(IDictionary<string, string>))]
[JsonSerializable(typeof(IList<PluginPrivilege>))]
[JsonSerializable(typeof(IList<string>))]
[JsonSerializable(typeof(ImageHistoryResponse[]))]
[JsonSerializable(typeof(ImageInspectResponse))]
[JsonSerializable(typeof(ImageSearchResponse[]))]
[JsonSerializable(typeof(ImagesListResponse[]))]
[JsonSerializable(typeof(ImagesPruneResponse))]
[JsonSerializable(typeof(JSONMessage))]
[JsonSerializable(typeof(Message))]
[JsonSerializable(typeof(NetworkConnectParameters))]
[JsonSerializable(typeof(NetworkDisconnectParameters))]
[JsonSerializable(typeof(NetworkResponse[]))]
[JsonSerializable(typeof(NetworksCreateParameters))]
[JsonSerializable(typeof(NetworksCreateResponse))]
[JsonSerializable(typeof(NetworksCreateResponse))]
[JsonSerializable(typeof(NetworksPruneResponse))]
[JsonSerializable(typeof(NodeListResponse[]))]
[JsonSerializable(typeof(NodeUpdateParameters))]
[JsonSerializable(typeof(PluginPrivilege[]))]
[JsonSerializable(typeof(Plugin[]))]
[JsonSerializable(typeof(SecretCreateResponse))]
[JsonSerializable(typeof(SecretSpec))]
[JsonSerializable(typeof(Secret[]))]
[JsonSerializable(typeof(ServiceCreateResponse))]
[JsonSerializable(typeof(ServiceSpec))]
[JsonSerializable(typeof(ServiceUpdateResponse))]
[JsonSerializable(typeof(Spec))]
[JsonSerializable(typeof(SwarmConfigSpec))]
[JsonSerializable(typeof(SwarmConfig[]))]
[JsonSerializable(typeof(SwarmCreateConfigResponse))]
[JsonSerializable(typeof(SwarmInitParameters))]
[JsonSerializable(typeof(SwarmInspectResponse))]
[JsonSerializable(typeof(SwarmJoinParameters))]
[JsonSerializable(typeof(SwarmService))]
[JsonSerializable(typeof(SwarmService[]))]
[JsonSerializable(typeof(SwarmUnlockParameters))]
[JsonSerializable(typeof(SwarmUnlockResponse))]
[JsonSerializable(typeof(SystemInfoResponse))]
[JsonSerializable(typeof(TaskResponse[]))]
[JsonSerializable(typeof(VersionResponse))]
[JsonSerializable(typeof(VolumeResponse))]
[JsonSerializable(typeof(VolumesCreateParameters))]
[JsonSerializable(typeof(VolumesListResponse))]
[JsonSerializable(typeof(VolumesPruneResponse))]
[JsonSerializable(typeof(string))]
internal partial class DockerClientSerializerContext : JsonSerializerContext;